[package]
name = "dosdisassm"
version = "0.1.0"
edition = "2024"
authors = ["sk337 <me@pk3.zip>"]

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
disassembler = { version = "0.1.0", path = "../disassembler" }
