[package]
name = "wasm"
version = "0.1.2"
edition = "2024"
description = "WASM bindings for the disassembler"
publish = false

[dependencies]
disassembler = { version = "0.1.2", path = "../../disassembler" }
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"


[lib]
crate-type = ["cdylib"]
